---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oci-oke-lb-operator
  namespace: default
  labels:
    app: oci-oke-lb-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: oci-oke-lb-operator
  template:
    metadata:
      labels:
        app: oci-oke-lb-operator
    spec:
      serviceAccountName: oci-oke-lb-operator
      securityContext:
        runAsUser:
          1000
      imagePullSecrets:
      - name: ocirsecret
      containers:
      - env:
        - name: VERBOSE
          value: "false"
        - name: DEBUG
          value: "false"
        - name: NAMESPACE
          value: ALL
        - name: LIVENESS
          value: "true"
        name: kopf-operator
        image: <region-key>/<tenancy-namespace>/oci-oke-lb-operator:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          failureThreshold: 3
          periodSeconds: 30