---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oci-oke-lb-operator-cluster-role
rules:
  # for watching services
  - apiGroups: [""]
    resources: [services]
    verbs: [get, list, patch, update, watch]
  - apiGroups: [""]
    resources: [events]
    verbs: [create]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [list, watch]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oci-oke-lb-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oci-oke-lb-operator-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: oci-oke-lb-operator-cluster-role
subjects:
  - kind: ServiceAccount
    name: oci-oke-lb-operator
    namespace: default